// Standard error message
export const errorMessage =
  "Please ensure you are using this application in an 'Object View' and reload the page. If this remains unresolved, please contact the developers.";

export const mondayDataObj = {
  users: [],
};
export const navlinks = [
  {
    href: "/",
    text: "Entries",
  },
  {
    href: "/timesheets",
    text: "Timesheets",
  },
  // {
  //   href: "/automate",
  //   text: "Automate",
  // },
  {
    href: "/ratecards",
    text: "Ratecards",
  },
  {
    href: "/export",
    text: "Export",
  },
  {
    href: "/settings",
    text: "Settings",
  },
];

export const teams = [
  "All",
  "Finance",
  "Marketing",
  "Sales",
  "Operations",
  "HR",
  "IT",
];

export const nonUserGroups = ["All"];

export const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const totalHoursOptions = [
  {
    text: "Non-Billable",
    value: 2,
  },
  {
    text: "Billable",
    value: 1,
  },
  {
    text: "All",
    value: 0,
  },
];

export const hoursOptions = [
  { value: "0", label: "00:00" },
  { value: "1", label: "01:00" },
  { value: "2", label: "02:00" },
  { value: "3", label: "03:00" },
  { value: "4", label: "04:00" },
  { value: "5", label: "05:00" },
  { value: "6", label: "06:00" },
  { value: "7", label: "07:00" },
  { value: "8", label: "08:00" },
  { value: "9", label: "09:00" },
  { value: "10", label: "10:00" },
  { value: "11", label: "11:00" },
  { value: "12", label: "12:00" },
  { value: "13", label: "13:00" },
  { value: "14", label: "14:00" },
  { value: "15", label: "15:00" },
  { value: "16", label: "16:00" },
  { value: "17", label: "17:00" },
  { value: "18", label: "18:00" },
  { value: "19", label: "19:00" },
  { value: "20", label: "20:00" },
  { value: "21", label: "21:00" },
  { value: "22", label: "22:00" },
  { value: "23", label: "23:00" },
  { value: "24", label: "24:00" },
];
export const peopleList = [
  {
    name: "Steven Jacobs",
    role: "Developer",
    photoThumb: null,
    startTime: "09:00",
    endTime: "18:00",
    days: [1, 2, 3, 4, 5],
    rate: "180",
    currency: "GBP",
    team: "Marketing",
  },
  {
    name: "Anna Smith",
    role: "Marketing Manager",
    photoThumb: null,
    startTime: "08:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "Marketing",
  },
  {
    name: "Robert Brown",
    role: "Financial Analyst",
    photoThumb: null,
    startTime: "09:30",
    endTime: "18:30",
    days: [1, 2, 3, 4, 5],
    rate: "210",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "Emily Davis",
    role: "Operations Manager",
    photoThumb: null,
    startTime: "07:00",
    endTime: "16:00",
    days: [1, 2, 3, 4, 5],
    rate: "220",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Michael Thompson",
    role: "Operations Specialist",
    photoThumb: null,
    startTime: "06:00",
    endTime: "15:00",
    days: [1, 2, 3, 4, 5],
    rate: "190",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Linda Johnson",
    role: "HR Manager",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "210",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Chris Lee",
    role: "IT Support",
    photoThumb: null,
    startTime: "10:00",
    endTime: "19:00",
    days: [1, 2, 3, 4, 5],
    rate: "180",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Sarah Williams",
    role: "Sales Representative",
    photoThumb: null,
    startTime: "08:30",
    endTime: "17:30",
    days: [1, 2, 3, 4, 5],
    rate: "190",
    currency: "GBP",
    team: "Sales",
  },
  {
    name: "David Wilson",
    role: "Finance Manager",
    photoThumb: null,
    startTime: "09:00",
    endTime: "18:00",
    days: [1, 2, 3, 4, 5],
    rate: "230",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "Laura Martin",
    role: "HR Specialist",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Kevin Brown",
    role: "Marketing Analyst",
    photoThumb: null,
    startTime: "08:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "185",
    currency: "GBP",
    team: "Marketing",
  },
  {
    name: "Natalie Taylor",
    role: "IT Manager",
    photoThumb: null,
    startTime: "09:00",
    endTime: "18:00",
    days: [1, 2, 3, 4, 5],
    rate: "240",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Adam Evans",
    role: "Operations Coordinator",
    photoThumb: null,
    startTime: "07:30",
    endTime: "16:30",
    days: [1, 2, 3, 4, 5],
    rate: "195",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Laura Phillips",
    role: "Finance Specialist",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:30",
    days: [1, 2, 3, 4, 5],
    rate: "215",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "Matthew Harris",
    role: "Sales Manager",
    photoThumb: null,
    startTime: "08:30",
    endTime: "17:30",
    days: [1, 2, 3, 4, 5],
    rate: "220",
    currency: "GBP",
    team: "Sales",
  },
  {
    name: "Olivia Walker",
    role: "HR Coordinator",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Joshua Allen",
    role: "IT Specialist",
    photoThumb: null,
    startTime: "10:00",
    endTime: "19:00",
    days: [1, 2, 3, 4, 5],
    rate: "190",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Isabella Scott",
    role: "Marketing Coordinator",
    photoThumb: null,
    startTime: "08:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "180",
    currency: "GBP",
    team: "Marketing",
  },
  {
    name: "Ethan Robinson",
    role: "Operations Analyst",
    photoThumb: null,
    startTime: "07:00",
    endTime: "16:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Sophia Green",
    role: "Sales Specialist",
    photoThumb: null,
    startTime: "08:30",
    endTime: "17:30",
    days: [1, 2, 3, 4, 5],
    rate: "210",
    currency: "GBP",
    team: "Sales",
  },
  {
    name: "Daniel Edwards",
    role: "Finance Coordinator",
    photoThumb: null,
    startTime: "09:00",
    endTime: "18:00",
    days: [1, 2, 3, 4, 5],
    rate: "220",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "Charlotte Thomas",
    role: "HR Assistant",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "180",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Henry White",
    role: "IT Support",
    photoThumb: null,
    startTime: "10:00",
    endTime: "19:00",
    days: [1, 2, 3, 4, 5],
    rate: "185",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Amelia Young",
    role: "Marketing Specialist",
    photoThumb: null,
    startTime: "08:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "190",
    currency: "GBP",
    team: "Marketing",
  },
  {
    name: "Jack King",
    role: "Operations Manager",
    photoThumb: null,
    startTime: "07:30",
    endTime: "16:30",
    days: [1, 2, 3, 4, 5],
    rate: "230",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Ava Hill",
    role: "Finance Analyst",
    photoThumb: null,
    startTime: "09:30",
    endTime: "18:30",
    days: [1, 2, 3, 4, 5],
    rate: "210",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "James Wright",
    role: "HR Specialist",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Emily Harris",
    role: "IT Manager",
    photoThumb: null,
    startTime: "09:00",
    endTime: "18:00",
    days: [1, 2, 3, 4, 5],
    rate: "240",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Ryan Lewis",
    role: "Operations Coordinator",
    photoThumb: null,
    startTime: "07:30",
    endTime: "16:30",
    days: [1, 2, 3, 4, 5],
    rate: "195",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Zoe Clark",
    role: "Finance Specialist",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:30",
    days: [1, 2, 3, 4, 5],
    rate: "215",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "Samuel Baker",
    role: "Sales Manager",
    photoThumb: null,
    startTime: "08:30",
    endTime: "17:30",
    days: [1, 2, 3, 4, 5],
    rate: "220",
    currency: "GBP",
    team: "Sales",
  },
  {
    name: "Grace Adams",
    role: "HR Coordinator",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Benjamin Young",
    role: "IT Specialist",
    photoThumb: null,
    startTime: "10:00",
    endTime: "19:00",
    days: [1, 2, 3, 4, 5],
    rate: "190",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Sophia Martinez",
    role: "Marketing Coordinator",
    photoThumb: null,
    startTime: "08:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "180",
    currency: "GBP",
    team: "Marketing",
  },
  {
    name: "Ethan Rodriguez",
    role: "Operations Analyst",
    photoThumb: null,
    startTime: "07:00",
    endTime: "16:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Isabella Perez",
    role: "Sales Specialist",
    photoThumb: null,
    startTime: "08:30",
    endTime: "17:30",
    days: [1, 2, 3, 4, 5],
    rate: "210",
    currency: "GBP",
    team: "Sales",
  },
  {
    name: "Daniel Garcia",
    role: "Finance Coordinator",
    photoThumb: null,
    startTime: "09:00",
    endTime: "18:00",
    days: [1, 2, 3, 4, 5],
    rate: "220",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "Charlotte Taylor",
    role: "HR Assistant",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "180",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Henry Anderson",
    role: "IT Support",
    photoThumb: null,
    startTime: "10:00",
    endTime: "19:00",
    days: [1, 2, 3, 4, 5],
    rate: "185",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Ava Moore",
    role: "Marketing Specialist",
    photoThumb: null,
    startTime: "08:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "190",
    currency: "GBP",
    team: "Marketing",
  },
  {
    name: "Jack Lee",
    role: "Operations Manager",
    photoThumb: null,
    startTime: "07:30",
    endTime: "16:30",
    days: [1, 2, 3, 4, 5],
    rate: "230",
    currency: "GBP",
    team: "Operations",
  },
  {
    name: "Ava Hill",
    role: "Finance Analyst",
    photoThumb: null,
    startTime: "09:30",
    endTime: "18:30",
    days: [1, 2, 3, 4, 5],
    rate: "210",
    currency: "GBP",
    team: "Finance",
  },
  {
    name: "James Wright",
    role: "HR Specialist",
    photoThumb: null,
    startTime: "09:00",
    endTime: "17:00",
    days: [1, 2, 3, 4, 5],
    rate: "200",
    currency: "GBP",
    team: "HR",
  },
  {
    name: "Emily Harris",
    role: "IT Manager",
    photoThumb: null,
    startTime: "09:00",
    endTime: "18:00",
    days: [1, 2, 3, 4, 5],
    rate: "240",
    currency: "GBP",
    team: "IT",
  },
  {
    name: "Ryan Lewis",
    role: "Operations Coordinator",
    photoThumb: null,
    startTime: "07:30",
    endTime: "16:30",
    days: [1, 2, 3, 4, 5],
    rate: "195",
    currency: "GBP",
    team: "Operations",
  },
];
